### ISSUE TITLE
require normal processing of "optimize" option

### ISSUE THREAD

**Issue by comdiv** [jorrit/gulp-requirejs#10]
For now it explicitly set "none" that is very strange - in most cases we have to minimize result or have to choose optimization method

**Comment by jorrit** [comment]
I think the original author intended to use a dedicated plugin such as gulp-uglify to compress the output. Now that #20 is committed, you can actually chain gulp-uglify after gulp-requirejs.

**Comment by jorrit** [comment]
Was fixed with merging PR #4.
