### ISSUE TITLE
Is it possible to do incremental builds?

### ISSUE THREAD

**Issue by mukeshsoni** [jorrit/gulp-requirejs#15]
Currently, if i hook this up with a watcher (say gulp.watch), the whole build process repeats for all the files. Is it possible to cache the read files and not process the files which are not changed.

Something similar to what is suggested here - https://github.com/gulpjs/gulp/blob/master/docs/recipes/incremental-builds-with-concatenate.md

**Comment by jorrit** [comment]
r.js is a single job, it can't be split into smaller jobs that run on parts of the output.
