### ISSUE TITLE
Adding a baseUrl that's not the current when using almond.js causes unfindable reference

### ISSUE THREAD

**Issue by Sawtaytoes** [jorrit/gulp-requirejs#16]
When using a `baseUrl` of something such as `'app/'` and then setting `name` to `'almond.js'`, it will find the file and complain that it is looking from the project root `'.'` for almond.js.

My workaround was to put `almond.js` in both `app/` and `.`. Is there a better way to do this so I can have a custom `baseUrl` without having to double-up on `almond.js`?

**Comment by jorrit** [comment]
Is this still happening with the master version, which has updated dependencies?

**Comment by Sawtaytoes** [comment]
Hi @jorrit. I wish I could say, but it's been a long time since I last took a look at this issue, and I do not know the specifics of the setup I was using anymore.

**Comment by jorrit** [comment]
I can image that, thanks for letting me know though!
