### ISSUE TITLE
Outputting compiled files outside of gulpfile folder

### ISSUE THREAD

**Issue by ritchieanesco** [jorrit/gulp-requirejs#25]
Hi,

This is not so much a bug but I am trying to compile the files outside of the project folder however a 'mkdir' error appears, i'm assuming this is a precaution to prevent files outside of the project from accidentally being overridden. Is there an option i can use to allow me to do this?

**Comment by ritchieanesco** [comment]
Here's the requirejs config:

`                  optimize: 'uglify2',
                    preserveLicenseComments : false,
                    uglify2: {
                        // jscs:disable
                        compress: {
                            sequences: true,
                            conditionals: true,
                            booleans: true,
                            unused: true,
                            if_return: true,
                            join_vars: true,
                            global_defs: {
                                DEBUG: false
                            },
                            dead_code: true
                        }
                    },
                    appDir: 'source/assets/scripts/app',
                    baseUrl: './',
                    findNestedDependencies: false,
                    generateSourceMaps: false,
                    removeCombined: true,
                    dir: '../Website/assets/version1111111111/scripts/app',
                    mainConfigFile: 'source/assets/scripts/app/config.js',
                    paths: {
        'jquery': 'empty:',
        'handlebars': 'empty:'
},
                    modules:         {
            name: 'main',
            exclude: [
                'handlebars-compiler'
            ]
        }
`

For context my directories are set up as follows

- dev
|- gulpfile.js
|- source
  |- assets
    |- scripts
      |- app
- Website
|- assets (local assets) // target directory for local build


The error:

> npm ERR! Error: EACCES: permission denied, mkdir 'c:/w/ProjectName/Website/assets/version1111111111/scripts/app

My temporary fix is to compile out the require modules to a subdirectory that sits under the gulpfile.js. Then use the copy task to move files over to target directory.

**Comment by jorrit** [comment]
Also, is there a more complete stack trace?

**Comment by ritchieanesco** [comment]
Sorry for the late replies, as the files are on my work computer i wont be able to get you the stack trace until tomorrow. i'll try creating the directories manually and see if gulp complains.

**Comment by jorrit** [comment]
Any news @ritchieanesco ?

**Comment by jorrit** [comment]
Sorry, have to close this if you can't provide more information.
