### ISSUE TITLE
rewirte config out to function has a bug

### ISSUE THREAD

**Issue by FocusCare** [jorrit/gulp-requirejs#29]
code: 
// Set .out to a function to catch result text and sourcemap.
  opts.out = function(text, sourceMap) {
    output = text;
    sourceMapOutput = sourceMap;
  };

when i use gulp-requirejs and require-css, at require-css/css-builder.js line 130,
code:
siteRoot = path.resolve(config.dir || path.dirname(config.out), config.siteRoot || '.') + '/';

get an error TypeError: Path must be a string, becuse confg.out is a function.

**Comment by jorrit** [comment]
gulp-requirejs is created to work with requirejs, not require-css. Require.js supports a function as `out` parameter, see https://github.com/requirejs/r.js/blob/master/build/example.build.js#L448.

Could you post all relevant lines of your gulp config?

**Comment by FocusCare** [comment]
out config: 
{
                stubModules: ['text'],
                inlineText: true,
                findNestedDependencies: true,
                optimizeAllPluginResources: true,
                preserveLicenseComments: false,
                baseUrl: './' + item,
                name: 'main',
                out: './build/' + item + '.js',
                exclude: [
                    'text',
                    'backbone',
                    'underscore',
                    'jquery',
                    'Zepto',
                    'js/base/main',
                    'js/base_sdk/main',
                    'normalize',
                    'bower_components/ajax/ajax',
                    'Vue'
                ],
                pragmasOnSave: {
                    excludeRequireCss: true
                }
                // optimizeCss: true
            }
and the require-css config
paths: {
        'css': 'vendor/require-css-1.10/css',
        'css-builder': 'vendor/require-css-1.10/css-builder',
        'normalize': 'vendor/require-css-1.10/normalize'
}

**Comment by jorrit** [comment]
What happens if you add `dir: 'build'` to your config?

**Comment by FocusCare** [comment]
@jorrit I fixed it, it is bug of require-css. In require-css/css-builder.js check the type of config.out.
And thank you verymuch~

**Comment by jorrit** [comment]
ok, great to hear!

**Comment by anguila** [comment]
How did you solve this issue? I'm having the same problem..
