### ISSUE TITLE
Doesn't seem to work in my environment

### ISSUE THREAD

**Issue by navFooh** [jorrit/gulp-requirejs#38]
This sounds like the vaguest bug report, but I'm scratching my head at why the plugin doesn't seem to do anything for me. I've setup a super basic test with `gulp-debug`, all the files are in the root of a folder. Here we go:

package.json
```
{
  "name": "test",
  "version": "1.0.0",
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-debug": "^4.0.0",
    "gulp-requirejs": "^1.2.0"
  }
}
```

gulpfile.js
```
const gulp = require('gulp');
const debug = require('gulp-debug');
const rjs = require('gulp-requirejs');

gulp.task('requirejsBuild', function() {
    return rjs({
        baseUrl: 'main.js',
        out: 'main.min.js'
    })
    .pipe(debug())
    .pipe(gulp.dest('./deploy/'));
});
```

main.js
```
define('multiply', [], function() {
    return function(a, b) {
        return a * b;
    };
});

requirejs(['multiply'], function(multiply) {
    console.log('multiply:', multiply(3, 5));
});
```

Now, I don't get any output in a `./deploy/` directory, nor does `gulp-debug` log any files passing in the stream. I can enter any name in baseUrl (absolute paths, relative paths and non-existing paths), but it never seem to throw errors or give any output.

My node version is 10.11.0

Any idea what could be going on here?

Cheers, Thijs

**Comment by jorrit** [comment]
Can you make a GitHub repository with these files? Then I'll take a look.

**Comment by navFooh** [comment]
Here you go: https://github.com/navFooh/gulp-requirejs-test

**Comment by jorrit** [comment]
The documentation was unclear. The gulp task should be:

```js
gulp.task('requirejsBuild', function() {
    return rjs({
        baseUrl: '.',
        out: 'main.min.js',
        name: 'main'
    })
    .pipe(debug())
    .pipe(gulp.dest('./deploy/'));
});
```
