### ISSUE TITLE
Fails with "Unexpeced token ..." in Spread_syntax object merge

### ISSUE THREAD

**Issue by RedJabber** [jorrit/gulp-requirejs#40]
r.js fails on this constructions 
```
let a = {ina:1}
let b = {inb:2}
let c = {inc:3}
let x= {...a, ...b, ...c} //fails here 
```

[ mdn-ref ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Syntax)

at ..gulp-requirejs\node_modules\requirejs\bin\r.js:27689:47
v.2.3.5

**Comment by jorrit** [comment]
I think you should report this to the requirejs folks, this module is just a wrapper around the requirejs' r.js script. I think they will answer that you should process your clde using babel first.
