### ISSUE TITLE
baseURL

### ISSUE THREAD

**Issue by DmitryAuine** [jorrit/gulp-requirejs#9]
My app is hosted on cdn with certain url. For example http://cnd.com/app
in main.js 
require.config({
    baseUrl:  http://cnd.com/app',
...

When i use this plugin i set the baseURL to local files
rjs({
        baseUrl: "app",
        mainConfigFile: mainPath,
        out: "main.built.js",
        include: include
    })

So, after it, i get rewrited cdn baseURL to local baseURL.

**Comment by jorrit** [comment]
Could you describe what the problem is?

**Comment by DmitryAuine** [comment]
@jorrit oh sorry man :) It was a long time ago :)

**Comment by jorrit** [comment]
Don't worry, if you remember what it was I'd be happy to help. Otherwise maybe someone else will report it again.
